import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import SmoothScrolling from "@/components/smootth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anime Bliss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} scroll-smooth flex lg:py-10 py-5 xl:py-10 lg:px-28 px-8 md:px-10 min-h-screen overflow-x-hidden pt-6 flex-col bg-darkbg `}><SmoothScrolling><NavBar />{children}</SmoothScrolling></body>
    </html>
  );
}
